### ISSUE TITLE
Conversion only possible after Downloading(Supervisely Format)/Reuploading

### ISSUE THREAD

**Issue by PanterSoft** [supervisely-ecosystem/export-to-kitti-3d#13]
Hello,

I am Experiencing an Issue where I can only convert to KITTI 3D when I first download the Pointcloud Project in supervisely Format and then reupload the project (Nothing changed)

I get the following Warning while converting:
![Export_error](https://github.com/supervisely-ecosystem/export-to-kitti-3d/assets/96704103/af43cfbc-a189-4f38-8f1a-4d10618986b3)

This error gets only created on pcd files which where labeled.

Can Someone Help me with this ?

**Comment by almazgimaev** [comment]
Hello, @PanterSoft 
apologies for the delayed response. After the recent updates, you shouldn't encounter such difficulties. We've also added the ability to export episodes in KITTI format.
If you have any questions about ecosystem applications, feel free to ask us in the [Slack channel](https://supervise.ly/slack).
